### ISSUE TITLE
2.3.0: Fatal error building PDF with 1.6 theme

### ISSUE THREAD

**Issue by infotexture** [asciidoctor/asciidoctor-pdf#2343]
ℹ️ Followup to https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/1155.

We have a custom theme that was built for Asciidoctor PDF 1.6 and works fine on the CLI with 1.6.2, but fails with a fatal error with Asciidoctor PDF 2.3.0:

    $ asciidoctor-pdf index.adoc \
      -a pdf-theme=/path/to/asciidoctor-pdf-theme/exb-theme.yml \
      -a pdf-fontsdir=/path/to/asciidoctor-pdf-theme/fonts

    asciidoctor: WARNING: unknown variable reference in PDF theme: $base-font-size
    asciidoctor: WARNING: the literal theme category is deprecated; use the codespan category instead
    asciidoctor: WARNING: the outline-list theme category is deprecated; use the list category instead

    undefined method `-' for #<String:0x0000000122603a60>
    Did you mean?  -@
      Use --trace to show backtrace

_(The warnings are expected, since we haven't yet updated the theme to use the 2.x equivalent  keys, but we plan to do that soon.)_

⬇️ Here's a copy of the theme YAML for testing, in case there's something wrong with the theme syntax that triggers this error.

<details>
<summary><i>Click to view theme source</i></summary>

```yaml
# Custom ExB theme for Asciidoctor PDF output

# https://github.com/asciidoctor/asciidoctor-pdf/blob/main/docs/theming-guide.adoc

exb:
  # Brand color variables

  color-orange:       '#fb4938'
  color-purple:       '#5539b4'
  color-teal:         '#20b9b0'
  color-text-1:       '#1a0f3e'
  color-text-2:       '#464254'
  color-text-3:       '#656173'
  color-text-4:       '#9692a6'
  color-background-1: '#dedbea'
  color-background-2: '#f0eff6'

font:
  catalog:
    merge: false  # set value to true to merge catalog with theme you're extending
    PT_Sans:
      normal: PT_Sans/ptsans-normal.ttf
      italic: PT_Sans/ptsans-italic.ttf
      bold: PT_Sans/ptsans-bold.ttf
      bold_italic: PT_Sans/ptsans-bold_italic.ttf
    PT_Sans_Narrow:
      normal: PT_Sans_Narrow/ptsansnarrow-normal.ttf
      bold: PT_Sans_Narrow/ptsansnarrow-bold.ttf
    PT_Serif:
      normal: PT_Serif/ptserif-normal.ttf
      italic: PT_Serif/ptserif-italic.ttf
      bold: PT_Serif/ptserif-bold.ttf
      bold_italic: PT_Serif/ptserif-bold_italic.ttf
    M+ 1mn:
      normal: GEM_FONTS_DIR/mplus1mn-regular-subset.ttf
      bold: GEM_FONTS_DIR/mplus1mn-bold-subset.ttf
      italic: GEM_FONTS_DIR/mplus1mn-italic-subset.ttf
      bold_italic: GEM_FONTS_DIR/mplus1mn-bold_italic-subset.ttf
    M+ 1p Fallback: GEM_FONTS_DIR/mplus1p-regular-fallback.ttf
  fallbacks:
  - M+ 1mn
  - M+ 1p Fallback

page:
  layout: portrait
  margin: [20mm, 25mm, 20mm, 25mm]
  size: A4

base:
  font-color: $exb-color-text-1
  font-family: PT_Serif
  line-height-length: 20
  line-height: $base-line-height-length / $base-font-size

button:
  content: "%s"

link:
  font-color: $exb-color-teal

literal:
  font-family: M+ 1mn

heading:
  font-color: $exb-color-purple
  font-family: PT_Sans_Narrow
  font-size: 12
  font-style: bold
  h1-font-color: $exb-color-orange
  h1-font-size: 30
  h2-font-size: 24
  h3-font-size: 18
  h4-font-size: 16
  h5-font-size: 14
  h6-font-size: 12
  line-height: 1.2

title-page:
  align: left
  background-image: image:images/gradient_orange-purple_A4-portrait.png[]
  font-color: '#fff'
  font-family: PT_Sans_Narrow
  logo:
    image: image:images/exb-logo_white.svg[pdfwidth=17%]
    top: 2%
  title:
    font-family: PT_Sans_Narrow
    font-size: 68
    line-height: 1
    top: 58%
  subtitle:
    font-family: PT_Serif
    font-size: 24
    font-style: normal
    line-height: 1
    margin-top: 3
  authors:
    font-size: 12
    margin-top: 32

caption:
  align: center
  font-color: $exb-color-text-4
  font-family: PT_Sans
  font-size: 10

code:
  background-color: $exb-color-background-2
  font-family: M+ 1mn

conum:
  font-color: $exb-color-purple
  font-family: M+ 1mn
  line-height: 2

sidebar:
  background-color: $exb-color-background-2

image:
  align: center

outline-list:
  marker-font-color: $exb-color-purple

ulist:
  marker:
    font-color: $exb-color-purple
    font-size: 14
    line-height: 1.5

table:
  border-color: $exb-color-background-1
  cell:
    padding: [1, 8, 3, 8]
  font-size: 9.5
  font-family: PT_Sans
  grid-width: 0
  body:
    stripe-background-color: $exb-color-background-2
  head:
    background-color: $exb-color-background-2
    border-bottom-width: 1

header:
  font-color: $exb-color-text-4
  font-family: PT_Sans
  font-size: 10
  height: 20mm
  line-height: 1
  recto:
    right:
      content: '{document-title}'
  verso:
    right:
      content: '{document-title}'

footer:
  font-color: $exb-color-text-4
  font-family: PT_Sans
  font-size: 10
  height: 20mm
  line-height: 1
  recto: &shared_footer
    left:
      content: '{chapter-title}'
    center:
      content: '{classification-level}'
    right:
      content: '*{page-number}*'
  verso: *shared_footer

page-numbering-start-at: title

```
</details>

**Comment by mojavelinux** [comment]
The problem with this theme is that it is referring to a variable that is not defined:

```
  line-height: $base-line-height-length / $base-font-size
```

This should have never worked in any version of Asciidoctor PDF. You cannot divide by nil. What's missing is a declaration of this key:

```
base:
  font-size: 12
```

Please confirm whether this fixes the problem.

**Comment by mojavelinux** [comment]
> This should have never worked in any version of Asciidoctor PDF (but clearly it used to)

Aha. I see what it is. In Asciidoctor PDF 1.6.2, if you did not specify `extends`, it would extend the base theme (which sets the base-font-size to 12). Starting in Asciidoctor PDF 2.0, if you don't specify `extends`, it does not extend a theme. So one way to make your theme portable is to add:

```
extends: base
```

That's really the change you want.

I'll clarify that in the migration guide.

**Comment by mojavelinux** [comment]
For portability reasons, I've decided to go ahead and set a default value for base-font-size (12) if it's not otherwise specified. This should provide a smoother experience when migrating.

**Comment by mojavelinux** [comment]
I'll backport this change to the 2.3.x branch so it gets swept up in the next release.

**Comment by infotexture** [comment]
> For portability reasons, I've decided to go ahead and set a default value for base-font-size (12) if it's not otherwise specified. This should provide a smoother experience when migrating.

That's a good solution that should prevent others from stumbling over this issue until they get around to updating their themes for 2.x.

In the meantime, I can confirm that adding `extends: base` indeed allows our builds to complete successfully with 2.3.0.

Thanks for the quick fixes here — and for everything you do to continuously improve these essential tools. 

Your work is much appreciated. 🙇

**Comment by mojavelinux** [comment]
Thanks for the follow-up @infotexture! I really appreciate your time.

**Comment by infotexture** [comment]
Tested again with Asciidoctor 2.3.2, the fix resolves the issue even without adding `extends: base` to the old theme. 🎉 

Nice compatibility update. 🙂
